---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Debian | ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      notify:
      - Debian | restart ntpd
    - name: RHEL | ensure ntpd is at the latest version
      yum: pkg=ntp state=latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      notify:
      - RHEL | restart ntpd
  handlers:
    - name: RHEL | restart ntpd
      service: name=ntpd state=restarted
    - name: Debian | restart ntpd
      service: name=ntp state=restarted
  roles:
    - { role: geerlingguy.repo-epel, when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' }
    - { role: curator } 
