---
- name: include vars
  include_vars: "vars.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Elasticsearch Curator and required dependencies.
  pip: "name={{ item }}"
  with_items:
    - elasticsearch-curator
    - argparse

- name: Configure cron jobs for Elasticsearch Curator.
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
  with_items: "{{ elasticsearch_curator_cron_jobs }}"

- name: Create curator config
  template:
    src: curator.yml.j2
    dest: /root/curator.yml

- name: Create curator action file
  template:
    src: actionfile.yml.j2
    dest: /root/actionfile.yml
